import type { Entry } from "./types";

// Transcribed from the owner's bilingual menu, PDF spreads 2–4 and 7–9.
// No prices occur in public titles/descriptions: staff price hiding remains effective.
export const menuSource = "menu folder/nvo menu-1.pdf";
export const menuEdition = "2026-09-25";
type Row = [
  id: string,
  en: string,
  fr: string,
  price: number | null,
  enDescription: string,
  frDescription: string,
  preorder?: boolean,
];
const groups: { id: string; en: string; fr: string; rows: Row[] }[] = [
  {
    id: "rice",
    en: "Rice",
    fr: "Riz",
    rows: [
      [
        "jollof-beef",
        "Jollof rice, beef & plantain or chips",
        "Riz jollof, bœuf & plantain ou frites",
        2500,
        "Jollof rice with beef and your choice of plantain or chips.",
        "Riz jollof accompagné de bœuf et de plantain ou de frites, au choix.",
      ],
      [
        "jollof-turkey",
        "Jollof rice & turkey",
        "Riz jollof & dinde",
        3000,
        "Jollof rice served with turkey.",
        "Riz jollof accompagné de dinde.",
      ],
      [
        "jollof-chicken",
        "Jollof rice & chicken",
        "Riz jollof & poulet",
        2500,
        "Jollof rice served with chicken.",
        "Riz jollof accompagné de poulet.",
      ],
      [
        "fried-rice-beef",
        "Fried rice & beef",
        "Riz frit & bœuf",
        3000,
        "Fried rice served with beef.",
        "Riz frit accompagné de bœuf.",
      ],
      [
        "fried-rice-turkey",
        "Fried rice & turkey",
        "Riz frit & dinde",
        3500,
        "Fried rice served with turkey.",
        "Riz frit accompagné de dinde.",
      ],
      [
        "fried-rice-chicken",
        "Fried rice & chicken",
        "Riz frit & poulet",
        3000,
        "Fried rice served with chicken.",
        "Riz frit accompagné de poulet.",
      ],
      [
        "white-rice-banga",
        "White rice & Banga soup",
        "Riz blanc & soupe Banga",
        3500,
        "White rice paired with Banga soup.",
        "Riz blanc accompagné de soupe Banga.",
      ],
      [
        "white-rice-turkey",
        "White rice, stew & turkey",
        "Riz blanc, sauce & dinde",
        2500,
        "White rice with stew and turkey.",
        "Riz blanc accompagné de sauce et de dinde.",
      ],
      [
        "white-rice-turkey-egg",
        "White rice, stew, turkey & egg",
        "Riz blanc, sauce, dinde & œuf",
        3500,
        "White rice with stew, turkey and egg.",
        "Riz blanc accompagné de sauce, de dinde et d’un œuf.",
      ],
      [
        "rice-beans-buka",
        "Rice, beans & Buka stew",
        "Riz, haricots & sauce Buka",
        3500,
        "Rice and beans served with Buka stew.",
        "Riz et haricots accompagnés de sauce Buka.",
      ],
      [
        "asun-rice",
        "Asun rice",
        "Riz Asun",
        3500,
        "Asun rice, available by pre-order. Confirm preparation time with our team.",
        "Riz Asun sur commande. Confirmez le délai de préparation avec notre équipe.",
        true,
      ],
      [
        "village-rice",
        "Village rice",
        "Riz villageois",
        3500,
        "Village rice from the NVO menu.",
        "Le riz villageois de la carte NVO.",
      ],
      [
        "coconut-rice",
        "Coconut rice",
        "Riz à la noix de coco",
        3500,
        "Coconut rice, available by pre-order.",
        "Riz à la noix de coco, sur commande.",
        true,
      ],
      [
        "chinese-rice",
        "Chinese rice",
        "Riz chinois",
        5000,
        "Chinese rice, available by pre-order.",
        "Riz chinois, sur commande.",
        true,
      ],
      [
        "pineapple-rice",
        "Pineapple rice",
        "Riz à l’ananas",
        5000,
        "Pineapple rice, available by pre-order.",
        "Riz à l’ananas, sur commande.",
        true,
      ],
      [
        "peppered-rice",
        "Peppered rice",
        "Riz poivré",
        3500,
        "Peppered rice from the NVO menu.",
        "Le riz poivré de la carte NVO.",
      ],
    ],
  },
  {
    id: "other-menu",
    en: "Pasta & other favourites",
    fr: "Pâtes & autres spécialités",
    rows: [
      [
        "stir-fry-spaghetti",
        "Stir-fry spaghetti, egg & turkey",
        "Spaghettis sautés, œuf & dinde",
        3500,
        "Stir-fried spaghetti served with egg and turkey.",
        "Spaghettis sautés accompagnés d’un œuf et de dinde.",
      ],
      [
        "chips-turkey-combo",
        "Chips, turkey, plantain, egg & sausage",
        "Frites, dinde, plantain, œuf & saucisse",
        3500,
        "Chips with turkey, plantain, egg and sausage.",
        "Frites accompagnées de dinde, de plantain, d’un œuf et de saucisse.",
      ],
      [
        "peppered-noodles",
        "Peppered noodles, turkey, egg & sausage",
        "Nouilles poivrées, dinde, œuf & saucisse",
        3500,
        "Peppered noodles with turkey, egg and sausage.",
        "Nouilles poivrées accompagnées de dinde, d’un œuf et de saucisse.",
      ],
      [
        "yam-porridge",
        "Yam porridge",
        "Porridge d’igname",
        3500,
        "Yam porridge from the NVO kitchen.",
        "Le porridge d’igname de la cuisine NVO.",
      ],
      [
        "asun-spaghetti-option-1",
        "Asun spaghetti · option 1",
        "Spaghettis Asun · option 1",
        3000,
        "The first of two options on our menu. Please confirm the portion with our team before ordering.",
        "La première des deux formules de notre carte. Confirmez la portion avec notre équipe avant de commander.",
      ],
      [
        "asun-spaghetti-option-2",
        "Asun spaghetti · option 2",
        "Spaghettis Asun · option 2",
        7500,
        "The second of two options on our menu. Please confirm the portion with our team before ordering.",
        "La deuxième des deux formules de notre carte. Confirmez la portion avec notre équipe avant de commander.",
      ],
      [
        "attieke",
        "Attiéké",
        "Attiéké",
        3000,
        "Attiéké, listed as Atcheke on the printed menu. Ask our team about accompaniments.",
        "Attiéké, indiqué « Atcheke » sur la carte imprimée. Renseignez-vous sur les accompagnements.",
      ],
      [
        "couscous",
        "Couscous",
        "Couscous",
        2500,
        "Couscous from the NVO menu. Ask our team about accompaniments.",
        "Le couscous de la carte NVO. Renseignez-vous sur les accompagnements.",
      ],
      [
        "peppered-snail",
        "Peppered snail",
        "Escargots poivrés",
        5000,
        "Peppered snails from the NVO kitchen.",
        "Les escargots poivrés de la cuisine NVO.",
      ],
      [
        "gizzard-stew",
        "Gizzard stew",
        "Ragoût de gésiers",
        3500,
        "Gizzard stew from the NVO kitchen.",
        "Le ragoût de gésiers de la cuisine NVO.",
      ],
      [
        "yam-plantain-fish-sauce",
        "Yam, plantain & vegetable fish sauce",
        "Igname, plantain & sauce poisson aux légumes",
        3000,
        "Yam and plantain served with vegetable fish sauce.",
        "Igname et plantain accompagnés d’une sauce au poisson et aux légumes.",
      ],
      [
        "yam-plantain",
        "Yam & plantain",
        "Igname & plantain",
        3500,
        "Yam and plantain from the NVO menu.",
        "Igname et plantain de la carte NVO.",
      ],
    ],
  },
  {
    id: "pepper-soup",
    en: "Pepper soup",
    fr: "Soupes au poivre",
    rows: [
      [
        "chicken-pepper-soup",
        "Chicken pepper soup",
        "Soupe au poivre au poulet",
        3500,
        "Chicken pepper soup. Tell our team your preferred level of heat.",
        "Soupe au poivre au poulet. Indiquez à notre équipe votre préférence en matière de piment.",
      ],
      [
        "catfish-pepper-soup",
        "Catfish pepper soup",
        "Soupe au poivre au poisson-chat",
        5000,
        "Catfish pepper soup from the NVO kitchen.",
        "Soupe au poivre au poisson-chat de la cuisine NVO.",
      ],
      [
        "whole-catfish-pepper-soup",
        "Full catfish pepper soup",
        "Soupe au poivre au poisson-chat entier",
        7500,
        "Pepper soup with a whole catfish, available by pre-order.",
        "Soupe au poivre avec un poisson-chat entier, sur commande.",
        true,
      ],
      [
        "goat-pepper-soup",
        "Goat meat pepper soup",
        "Soupe au poivre à la viande de chèvre",
        3500,
        "Goat meat pepper soup from the NVO kitchen.",
        "Soupe au poivre à la viande de chèvre de la cuisine NVO.",
      ],
    ],
  },
  {
    id: "soups",
    en: "Nigerian soups",
    fr: "Soupes nigérianes",
    rows: [
      [
        "ogbono-okra",
        "Ogbono / okra soup",
        "Soupe Ogbono / soupe de gombo",
        3500,
        "Choose Ogbono or okra soup. Confirm your preferred swallow and any additional cost with our team.",
        "Choisissez la soupe Ogbono ou la soupe de gombo. Confirmez l’accompagnement et tout supplément avec notre équipe.",
      ],
      [
        "vegetable",
        "Vegetable soup",
        "Soupe de légumes",
        3500,
        "Vegetable soup from the NVO menu. Confirm your preferred swallow with our team.",
        "Soupe de légumes de la carte NVO. Confirmez votre accompagnement avec notre équipe.",
      ],
      [
        "afang",
        "Afang soup",
        "Soupe Afang",
        3500,
        "Afang soup. Confirm your preferred swallow with our team.",
        "Soupe Afang. Confirmez votre accompagnement avec notre équipe.",
      ],
      [
        "eforiro",
        "Eforiro soup",
        "Soupe Eforiro",
        3500,
        "Eforiro soup. Confirm your preferred swallow with our team.",
        "Soupe Eforiro. Confirmez votre accompagnement avec notre équipe.",
      ],
      [
        "egusi",
        "Egusi soup",
        "Soupe Egusi",
        3500,
        "Egusi soup. Confirm your preferred swallow with our team.",
        "Soupe Egusi. Confirmez votre accompagnement avec notre équipe.",
      ],
      [
        "banga",
        "Banga soup",
        "Soupe Banga",
        3500,
        "Banga soup from the NVO kitchen. Choose your swallow with our team; accompaniment pricing is confirmed separately.",
        "Soupe Banga de la cuisine NVO. Choisissez votre accompagnement avec notre équipe ; son prix est à confirmer séparément.",
      ],
      [
        "oha",
        "Oha soup",
        "Soupe Oha",
        3500,
        "Oha soup. Confirm your preferred swallow with our team.",
        "Soupe Oha. Confirmez votre accompagnement avec notre équipe.",
      ],
      [
        "bitterleaf",
        "Bitterleaf soup",
        "Soupe aux feuilles amères",
        3500,
        "Bitterleaf soup. Confirm your preferred swallow with our team.",
        "Soupe aux feuilles amères. Confirmez votre accompagnement avec notre équipe.",
      ],
      [
        "ewedu",
        "Ewedu soup",
        "Soupe Ewedu",
        3500,
        "Ewedu soup. Confirm your preferred swallow with our team.",
        "Soupe Ewedu. Confirmez votre accompagnement avec notre équipe.",
      ],
      [
        "white-nsala",
        "White Nsala soup",
        "Soupe blanche Nsala",
        3500,
        "White Nsala soup. Confirm your preferred swallow with our team.",
        "Soupe blanche Nsala. Confirmez votre accompagnement avec notre équipe.",
      ],
    ],
  },
  {
    id: "swallow",
    en: "Swallow & accompaniments",
    fr: "Pâtes & accompagnements",
    rows: [
      ...["Starch", "Semo", "Fufu", "Eba", "Poundo", "Amala"].map(
        (name): Row => [
          "swallow-" + name.toLowerCase(),
          name,
          name,
          null,
          `${name} accompaniment. The printed menu does not specify a separate price; confirm with our team.`,
          `Accompagnement ${name}. Aucun prix distinct n’est indiqué sur la carte imprimée ; à confirmer avec notre équipe.`,
        ],
      ),
    ],
  },
  {
    id: "bbq",
    en: "BBQ · pre-order",
    fr: "Barbecue · sur commande",
    rows: [
      [
        "bbq-turkey",
        "BBQ turkey",
        "Dinde au barbecue",
        5000,
        "Barbecued turkey, available by pre-order.",
        "Dinde au barbecue, sur commande.",
        true,
      ],
      [
        "bbq-chicken",
        "BBQ chicken",
        "Poulet au barbecue",
        5000,
        "Barbecued chicken, available by pre-order.",
        "Poulet au barbecue, sur commande.",
        true,
      ],
      [
        "bbq-catfish-option-1",
        "BBQ catfish · option 1",
        "Poisson-chat au barbecue · option 1",
        10000,
        "The first catfish option on the printed menu. Pre-order and confirm the fish size with our team.",
        "La première formule poisson-chat de la carte imprimée. Sur commande ; taille à confirmer avec notre équipe.",
        true,
      ],
      [
        "bbq-catfish-option-2",
        "BBQ catfish · option 2",
        "Poisson-chat au barbecue · option 2",
        15000,
        "The second catfish option on the printed menu. Pre-order and confirm the fish size with our team.",
        "La deuxième formule poisson-chat de la carte imprimée. Sur commande ; taille à confirmer avec notre équipe.",
        true,
      ],
      [
        "bbq-other-fish",
        "Other BBQ fish",
        "Autres poissons au barbecue",
        null,
        "Fish and price vary by size. Pre-order with our team for the available fish and a confirmed quote.",
        "Poissons et prix variables selon la taille. Contactez notre équipe pour connaître les disponibilités et obtenir un devis.",
        true,
      ],
    ],
  },
  {
    id: "fast-food",
    en: "Shawarma",
    fr: "Shawarmas",
    rows: [
      [
        "shawarma-chicken",
        "Chicken shawarma",
        "Shawarma au poulet",
        2000,
        "Shawarma with chicken.",
        "Shawarma au poulet.",
      ],
      [
        "shawarma-turkey",
        "Turkey shawarma",
        "Shawarma à la dinde",
        2500,
        "Shawarma with turkey.",
        "Shawarma à la dinde.",
      ],
      [
        "shawarma-beef",
        "Beef shawarma",
        "Shawarma au bœuf",
        2000,
        "Shawarma with beef.",
        "Shawarma au bœuf.",
      ],
      [
        "shawarma-small",
        "Small shawarma",
        "Petit shawarma",
        1500,
        "A small shawarma. Confirm the available filling with our team.",
        "Un petit shawarma. Confirmez la garniture disponible avec notre équipe.",
      ],
    ],
  },
  {
    id: "seafood",
    en: "Seafood",
    fr: "Fruits de mer",
    rows: [
      [
        "seafood-noodles",
        "Seafood noodles",
        "Nouilles aux fruits de mer",
        5000,
        "Noodles with seafood. Ask our team about the day’s seafood selection.",
        "Nouilles aux fruits de mer. Renseignez-vous sur la sélection du jour.",
      ],
      [
        "seafood-spaghetti",
        "Seafood spaghetti",
        "Spaghettis aux fruits de mer",
        7500,
        "Spaghetti with seafood. Ask our team about the day’s seafood selection.",
        "Spaghettis aux fruits de mer. Renseignez-vous sur la sélection du jour.",
      ],
      [
        "peppered-prawns-option-1",
        "Medium peppered prawns · option 1",
        "Crevettes poivrées, portion moyenne · option 1",
        6000,
        "The first medium-prawn option on our menu. Confirm the portion with our team.",
        "La première formule de crevettes poivrées en portion moyenne. Portion à confirmer avec notre équipe.",
      ],
      [
        "peppered-prawns-option-2",
        "Medium peppered prawns · option 2",
        "Crevettes poivrées, portion moyenne · option 2",
        10000,
        "The second medium-prawn option on our menu. Confirm the portion with our team.",
        "La deuxième formule de crevettes poivrées en portion moyenne. Portion à confirmer avec notre équipe.",
      ],
      [
        "peppered-prawn-platter",
        "Big platter of peppered prawns",
        "Grand plateau de crevettes poivrées",
        15000,
        "A large platter of peppered prawns.",
        "Un grand plateau de crevettes poivrées.",
      ],
      [
        "seafood-soup-small",
        "Seafood Banga / okra soup · small",
        "Soupe Banga / gombo aux fruits de mer · petite",
        5000,
        "Small seafood soup option. Confirm Banga or okra with our team.",
        "Petite portion de soupe aux fruits de mer. Confirmez Banga ou gombo avec notre équipe.",
      ],
      [
        "seafood-soup-medium",
        "Seafood Banga / okra soup · medium",
        "Soupe Banga / gombo aux fruits de mer · moyenne",
        7500,
        "Medium seafood soup option. Confirm Banga or okra with our team.",
        "Portion moyenne de soupe aux fruits de mer. Confirmez Banga ou gombo avec notre équipe.",
      ],
      [
        "seafood-soup-standard",
        "Seafood Banga / okra soup · standard",
        "Soupe Banga / gombo aux fruits de mer · standard",
        10000,
        "Standard seafood soup option. Confirm Banga or okra with our team.",
        "Portion standard de soupe aux fruits de mer. Confirmez Banga ou gombo avec notre équipe.",
      ],
      [
        "fisherman-soup",
        "Fisherman soup",
        "Soupe du pêcheur",
        7500,
        "Fisherman soup. Ask our team about the seafood selection.",
        "Soupe du pêcheur. Renseignez-vous sur la sélection de fruits de mer.",
      ],
      [
        "fisherman-soup-premium",
        "Premium fisherman soup",
        "Soupe du pêcheur · formule premium",
        15000,
        "The premium fisherman soup package from the NVO menu.",
        "La formule premium de soupe du pêcheur de la carte NVO.",
      ],
      [
        "octopus",
        "Octopus",
        "Poulpe",
        null,
        "Octopus, listed on the French menu. Price varies; contact our team for availability and a quote.",
        "Poulpe, indiqué sur la carte française. Prix variable ; contactez notre équipe pour les disponibilités et un devis.",
      ],
    ],
  },
  {
    id: "seafood-packages",
    en: "Seafood boils & packages",
    fr: "Plateaux & assortiments de fruits de mer",
    rows: [
      [
        "seafood-boil-small",
        "Seafood boil · small pack",
        "Plateau de fruits de mer · petit assortiment",
        15000,
        "Prawns, crabs, boiled eggs, sausage and corn, with a side of noodles, rice or sweet potatoes.",
        "Crevettes, crabes, œufs durs, saucisse et maïs, avec des nouilles, du riz ou des patates douces en accompagnement.",
      ],
      [
        "seafood-boil-standard",
        "Seafood boil · standard package",
        "Plateau de fruits de mer · assortiment standard",
        30000,
        "Medium prawns, crabs, boiled eggs, sweet corn and sausage, with a side of fries.",
        "Crevettes moyennes, crabes, œufs durs, maïs doux et saucisse, avec des frites en accompagnement.",
      ],
      [
        "seafood-boil-deluxe",
        "Seafood boil · deluxe package",
        "Plateau de fruits de mer · assortiment deluxe",
        50000,
        "Big and medium prawns, shrimps, crabs, squid or octopus, smoked sausage, boiled eggs and sweet corn, with fries or noodles.",
        "Grosses et moyennes crevettes, petites crevettes, crabes, calamar ou poulpe, saucisse fumée, œufs durs et maïs doux, avec des frites ou des nouilles.",
      ],
      [
        "seafood-boil-premium",
        "Seafood boil · premium package",
        "Plateau de fruits de mer · assortiment premium",
        100000,
        "Prawns, shrimps, crabs, squid or octopus, grilled fish, snails, smoked sausage, boiled eggs, sweet corn, lobster and mussels, with fries or noodles.",
        "Crevettes, petites crevettes, crabes, calamar ou poulpe, poisson grillé, escargots, saucisse fumée, œufs durs, maïs doux, homard et moules, avec des frites ou des nouilles.",
      ],
    ],
  },
  {
    id: "extras",
    en: "Extras",
    fr: "Suppléments",
    rows: [
      [
        "extra-fried-rice",
        "Extra fried rice",
        "Supplément de riz frit",
        1000,
        "An extra serving of fried rice.",
        "Une portion supplémentaire de riz frit.",
      ],
      [
        "extra-protein",
        "Extra protein",
        "Supplément de protéines",
        1000,
        "Extra protein. Confirm the available choice with our team.",
        "Supplément de protéines. Confirmez le choix disponible avec notre équipe.",
      ],
      [
        "extra-sauce",
        "Extra sauce",
        "Supplément de sauce",
        1000,
        "An extra serving of sauce.",
        "Une portion supplémentaire de sauce.",
      ],
      [
        "extra-plantain",
        "Extra plantain",
        "Supplément de plantain",
        1000,
        "An extra serving of plantain.",
        "Une portion supplémentaire de plantain.",
      ],
      [
        "extra-chips",
        "Extra chips",
        "Supplément de frites",
        1000,
        "An extra serving of chips.",
        "Une portion supplémentaire de frites.",
      ],
    ],
  },
];

export const currentMenu: Entry[] = groups.flatMap((group, groupIndex) => [
  {
    id: group.id,
    kind: "categories" as const,
    title: group.en,
    titleFr: group.fr,
    description: "",
    active: true,
    sort: groupIndex + 1,
  },
  ...group.rows.map(
    (
      [id, title, titleFr, price, description, descriptionFr, preorder],
      index,
    ): Entry => ({
      id,
      kind: "meals",
      title,
      titleFr,
      price,
      description,
      descriptionFr,
      category: group.id,
      active: true,
      available: true,
      status: "published",
      priceVisibility: "inherit",
      sort: (groupIndex + 1) * 100 + index,
      preorder: !!preorder,
      featured: ["jollof-beef", "banga", "peppered-snail"].includes(id),
      image:
        id === "banga"
          ? "/images/banga.jpeg"
          : id === "vegetable"
            ? "/images/soup.jpeg"
            : id === "peppered-snail"
              ? "/images/peppered-bites.webp"
              : id === "jollof-beef"
                ? "/images/menu-jollof.webp"
                : id === "shawarma-chicken"
                  ? "/images/menu-shawarma.webp"
                  : id === "extra-plantain"
                    ? "/images/menu-plantain.webp"
                    : undefined,
    }),
  ),
]);
