import type { Entry, Settings } from "./types";
export const initialSettings: Settings = {
  name: "NVO Restaurant",
  whatsapp: "22950924184",
  address: "Commissariat, Agblangandan, Cotonou, Bénin",
  mapsUrl: "https://www.google.com/maps?cid=5172180877275416931",
  latitude: 6.3729882,
  longitude: 2.4852719,
  showPrices: false,
  currency: "XOF",
  email: "",
  hours: "",
  instagram: "https://www.instagram.com/nvo_benin/",
  referralEnabled: false,
  referralCampaign: "",
  referralClaimMinutes: 5,
};
export const initialEntries: Entry[] = [
  {
    id: "soups",
    kind: "categories",
    title: "Soups & swallow",
    titleFr: "Soupes & accompagnements",
    description: "",
    active: true,
    sort: 1,
  },
  {
    id: "rice",
    kind: "categories",
    title: "Rice & favourites",
    titleFr: "Riz & incontournables",
    description: "",
    active: true,
    sort: 2,
  },
  {
    id: "seafood",
    kind: "categories",
    title: "Seafood",
    titleFr: "Poissons & fruits de mer",
    description: "",
    active: true,
    sort: 3,
  },
  {
    id: "drinks",
    kind: "categories",
    title: "Drinks",
    titleFr: "Boissons",
    description: "",
    active: true,
    sort: 4,
  },
  {
    id: "banga",
    kind: "meals",
    title: "Banga soup & starch",
    titleFr: "Soupe Banga & starch",
    description:
      "A comforting NVO favourite. Ask us about today’s accompaniments and portions.",
    descriptionFr:
      "Un incontournable de NVO. Découvrez les accompagnements et portions disponibles.",
    category: "soups",
    image: "/images/banga.jpeg",
    price: null,
    priceVisibility: "inherit",
    active: true,
    available: true,
    featured: true,
    badge: "NVO favourite",
    sort: 1,
  },
  {
    id: "rice-fish",
    kind: "meals",
    title: "Rice, fish & plantain",
    titleFr: "Riz, poisson & plantain",
    description:
      "A generous combination, with prawns and golden plantain. Prepared for your next delicious moment.",
    descriptionFr:
      "Une généreuse combinaison de riz, poisson, crevettes et plantain doré.",
    category: "rice",
    image: "/images/rice-fish.jpeg",
    price: null,
    priceVisibility: "inherit",
    active: true,
    available: true,
    featured: true,
    sort: 2,
  },
  {
    id: "vegetable",
    kind: "meals",
    title: "Vegetable soup",
    titleFr: "Soupe de légumes",
    description:
      "Rich, hearty and full of flavour. Choose your preferred accompaniment with our team.",
    descriptionFr:
      "Une soupe généreuse et savoureuse. Choisissez votre accompagnement avec notre équipe.",
    category: "soups",
    image: "/images/soup.jpeg",
    price: null,
    priceVisibility: "inherit",
    active: true,
    available: true,
    featured: true,
    sort: 3,
  },
  {
    id: "fish-rice",
    kind: "meals",
    title: "Fish rice",
    titleFr: "Riz au poisson",
    description:
      "Rice and fish, brought together in a satisfying plate. Contact us for availability.",
    descriptionFr:
      "Le riz et le poisson réunis dans une assiette gourmande. Contactez-nous pour la disponibilité.",
    category: "rice",
    image: "/images/fish-rice.jpeg",
    price: null,
    priceVisibility: "inherit",
    active: true,
    available: true,
    featured: false,
    sort: 4,
  },
  {
    id: "coke",
    kind: "meals",
    title: "Coca-Cola · 50 cl",
    titleFr: "Coca-Cola · 50 cl",
    description: "Something refreshing to go with your meal.",
    descriptionFr: "Une touche de fraîcheur pour accompagner votre repas.",
    category: "drinks",
    image: "/images/drinks.jpeg",
    price: null,
    priceVisibility: "inherit",
    active: true,
    available: true,
    sort: 5,
  },
];
